# https://cloud.google.com/deploy/docs/using-skaffold/getting-started-skaffold#have_generate_your_skaffoldyaml
apiVersion: skaffold/v4beta7
kind: Config
manifests:
  rawYaml:
    - vr-*
deploy:
  kubectl: {}
