# https://cloud.google.com/deploy/docs/using-skaffold/getting-started-skaffold#have_generate_your_skaffoldyaml
apiVersion: skaffold/v4beta7
kind: Config
# manifests:
#   rawYaml: [ "vr-*" ]
# deploy: { kubectl: {} }

# build:
#   artifacts:
#     - image: europe-west3-docker.pkg.dev/olehdevua-vr-nest/vr-nest-repo/vr-back
#       # context: ../../vr-back/src # Specify context if not root
#       # alias: vrBack # Optional alias for simpler setValueTemplates if needed
#
#   # - image: europe-west3-docker.pkg.dev/olehdevua-vr-nest/vr-nest-repo/vr-identity
#   #   context: ./path/to/vr-identity/src
#   #   alias: vrIdentity

manifests:
  helm:
    releases:
      - name: vr-project-chart # Helm release name for the entire project
        chartPath: ./vr-project-chart # Path to your umbrella chart directory
        # Skaffold will attempt to automatically set image tags.
        # For this to work well, the 'image.repository' in your umbrella chart's values
        # (e.g., vr-project-chart/values.yaml under 'vr-back.image.repository')
        # should match the Skaffold artifact image name.
        #
        # Example:
        # vr-project-chart/values.yaml:
        # vr-back:
        #   image:
        #     repository: europe-west3-docker.pkg.dev/olehdevua-vr-nest/vr-nest-repo/vr-back
        #     tag: "default-tag" # Skaffold will override this tag
        #
        # If auto-injection doesn't work as expected or for more control:
        setValueTemplates:
          # For the vr-back service:
          # The key 'vr-back.image.tag' targets the tag for the vr-back subchart.
          # '{{.IMAGE_TAG_europe_west3_docker_pkg_dev_olehdevua_vr_nest_vr_nest_repo_vr_back}}'
          # refers to the tag of the artifact with that specific image name.
          # If you used an alias like 'vrBack' in the build section: '{{.IMAGE_TAG_vrBack}}'
          "vr-back.image.tag": "{{.TAGS.europe_west3_docker_pkg_dev_olehdevua_vr_nest_vr_nest_repo_vr_back}}" # Or use alias if defined

          # When you add vr-identity (assuming its full image name):
          # "vr-identity.image.tag": "{{.TAGS.europe_west3_docker_pkg_dev_olehdevua_vr_nest_vr_nest_repo_vr_identity}}"
          # "vr-identity.enabled": "true" # You might want to enable it via Skaffold too
        # setValues: # Use for static overrides not dependent on build artifacts
        #   "vr-back.replicaCount": 3
