apiVersion: v1
kind: Service
metadata:
  name: {{ include "vr-back.fullname" . }}
  labels:
    {{- include "vr-back.labels" . | nindent 4 }}
    service: {{ include "vr-back.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
#     targetPort: http
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "vr-back.selectorLabels" . | nindent 4 }}
