# apiVersion: external-secrets.io/v1
# kind: SecretStore
# metadata:
#   name: gcp-secret-store       # Choose a name for your SecretStore
#   namespace: external-secrets # Namespace where this SecretStore and the auth secret reside
# spec:
#   provider:
#     gcpsm: # Google Cloud Platform Secret Manager
#       projectID: "olehdevua-vr-nest"
#       auth:
#         secretRef:
#           # k8s secret containing GSA key
#           secretAccessKeySecretRef:
#             name: "gcp-eso-sa-key"
#             key: "credentials.json"
# ---
apiVersion: external-secrets.io/v1 # Use the API version your ESO installation supports
kind: ClusterSecretStore
metadata:
  name: gcp-secret-store
spec:
  provider:
    gcpsm: # Google Cloud Platform Secret Manager
      projectID: "olehdevua-vr-nest"
      auth:
        secretRef:
          # k8s secret containing GSA key.
          # This secret must be in the namespace where ESO is running (e.g., external-secrets)
          secretAccessKeySecretRef:
            name: "gcp-eso-sa-key"
            key: "credentials.json"
            namespace: external-secrets # Namespace where the 'gcp-eso-sa-key' secret is located
