# kubectl create secret generic gcp-eso-sa-key \
#   --from-file=credentials.json=./gcp-credentials.json \
#   -n external-secrets

apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-store
# namespace: external-secrets # Namespace where this `SecretStore` and the auth secret reside
spec:
  provider:
    gcpsm: # Google Cloud Platform Secret Manager
      projectID: "olehdevua-vr-nest"
      auth:
        secretRef:
          # k8s secret containing a GSA key.
          # this secret must be in the namespace where ESO is running (e.g., external-secrets)
          secretAccessKeySecretRef:
            name: "gcp-eso-sa-key"
            key: "credentials.json"
            # namespace where the 'gcp-eso-sa-key' secret is located (only for ClusterSecretStore)
            namespace: external-secrets
