apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pg-external-secret
  namespace: default
spec:
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: pg-secret
    creationPolicy: Owner
    template:
      metadata:
        labels: { app: "pg" }
# data:
#   - secretKey: database_password
#     remoteRef:
#       key: vr-nest-pg-password # GSM secret name
  data:
    - secretKey: username
      remoteRef:
        key: vr-nest-pg-password  # Name of the secret in Google Secret Manager
        property: username        # Extract the 'username' field from the JSON in GSM
    - secretKey: password
      remoteRef:
        key: vr-nest-pg-password  # Name of the secret in Google Secret Manager
        property: password        # Extract the 'password' field from the JSON in GSM
