apiVersion: v1
kind: Service
metadata:
  name: {{ include "vr-back-chart.fullname" . }}
  labels:
    {{- include "vr-back-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "vr-back-chart.selectorLabels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.targetPort }}
      name: api
  selector:
    service: {{ .Release.Name }} # Or a more specific label from your deployment
  clusterIP: {{ .Values.service.clusterIP | default "None" }}
