name: Integration Tests DC

on:
  push:
    branches: [ main, 'epic-*' ]
  pull_request:
    branches: [ main, 'epic-*' ]

env:
  VR_BACK_IMAGE_NAME: vr-back

jobs:
  call-test:
    uses: ./.github/workflows/job-test.yaml

  call-build-and-push:
    uses: ./.github/workflows/job-build-n-push.yaml
    needs: call-test
    secrets:
      GCP_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
      GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      GAR_LOCATION: ${{ secrets.GAR_LOCATION }}
