name: Integration Tests DC

on:
  push:
    branches: [ main, 'epic-*' ]
  pull_request:
    branches: [ main, 'epic-*' ]

jobs:
  call-test:
    uses: ./.github/workflows/job-test.yaml

  call-build-and-push:
    uses: ./.github/workflows/job-build-n-push.yaml
    needs: call-test
    permissions:
      id-token: write
      contents: read
    secrets:
      GCP_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
      GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      GAR_LOCATION: ${{ secrets.GAR_LOCATION }}
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GAR_REPOSITORY: ${{ secrets.GAR_REPOSITORY }}
